#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Nagios-Plugins
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                  S e m g r e p   C l o u d   W o r k f l o w
# ============================================================================ #

# Logs results to https://semgrep.dev/

---
name: Semgrep Cloud

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  semgrep:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Semgrep Cloud
    uses: HariSekhon/GitHub-Actions/.github/workflows/semgrep-cloud.yaml@master
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    with:
      debug: ${{ github.event.inputs.debug }}
